#!/bin/env python3

# Program used to track and manage your tasks

import parser
import file_checker
import args_handler

# Parse arguments from a user
args = parser.parse_arguments()

tasks_json = 'tasks.json'

# Create a new file if not existing or empty
file_checker.create_file_if_missing(tasks_json)

# Handle passed arguments
args_handler.handle(args, tasks_json)